#! /bin/sh

# grub-install wrapper for use in SWIN.exe installations. This arranges for the
# grub bootloader installed on the host (yldr) to be reinstalled rather
# than installing it to a boot sector.
#
# To get at the real MBR if you wish to do so, use grub-install.real
# instead.
#
# Copyright (C) 2009 Canonical Ltd.
#
# Lupin is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Lupin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lupin; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301, USA.

if /usr/share/lupin-support/grub-mkimage --test; then
    grub-install.real --grub-probe=/usr/share/lupin-support/grub-probe --grub-setup=/bin/true --grub-mkimage=/usr/share/lupin-support/grub-mkimage "$@"
else
    grub-install.real "$@"
fi
